.travis.yml
Ruby 1.9.3 のサボートが終了したためTravis CIの設定から削除しました。
=> Drop 1.9.3

lib/bitclust/subcommands/setup_command.rb
Hi.
I'm try to use refe2 with windows and my ENV['HOME'] is "C:\\home", contains backslash
to divide file path components.
With such environment, refe2 is fail because BitClust::Searcher parse `config[:detabase_prefix]',
contains a value of ENV['HOME'] by default, as part of URI.
So I couldn't use refe2 without editing `~/.bitclust/config' at first.
In this patch, when creating default config file, apply Pathname#expand_path in order to normalize
"backslashed-filepath".
=> normalize Pathname from ENV['HOME']

bitclust-dev.gemspec, bitclust.gemspec, refe2.gemspec
I tried to use HEAD revision of rurema-search. But it shows dependency error when I invoke `bundle install`
```
(snip)
DEBUG [8cd53a1a] Command: cd /var/rubydoc/rurema-search/releases/20160514003652 && ( export RBENV_ROOT="/home/rurema/.rbenv" RBENV_VERSION="2.3.1" ; /home/rurema/.rbenv/bin/rbenv exec bundle install --path /var/rubydoc/rurema-search/shared/bundle --without development test --deployment --quiet )
DEBUG [8cd53a1a]       There was a LoadError while loading bitclust-dev.gemspec:
cannot load such file -- rake from
/var/rubydoc/rurema-search/shared/bundle/ruby/2.3.0/bundler/gems/bitclust-6db8204b56cb/bitclust-dev.gemspec:3:in
`<main>'
Does it try to require a relative path? That's been removed in Ruby 1.9.
```
It caused that `rake` is removed from stdlib at Ruby 2.3. I removed …
=> Remove rake dependency from gemspecs

lib/bitclust/subcommands/chm_command.rb
- hhp, hhc, hhk ファイルのエンコーディングを Windows-31J 固定へ変更
- hhc, hhk ファイルに meta タグ追加
- html ファイルのエンコーディングを可能な限り Windows-31J へ変更
- カタログディレクトリのデフォルト指定追加
- encode('windows-31j') でエラーになる文字を可能な限り、MSのUnicode文字へ置き換え
=> chmファイル生成方法変更

lib/bitclust/compat.rb
I faced deprecated warning with Ruby 2.4.0 on docs.ruby-lang.org. Like
`/var/rubydoc/bitclust/lib/bitclust/compat.rb:17: warning: constant ::Fixnum is deprecated`
`Fixnum.method_defined?(:ord)` is only false before Ruby 1.8.7.  so Ruby 1.8.6 is already EOL. We should remove this code.
=> Removed compatibility hack for old rubies.

lib/bitclust/rdcompiler.rb, test/test_rdcompiler.rb
https://github.com/rurema/doctree/pull/598 の作業中に ARGF 関連のるりまの記事から
rdoc へのリンクが軒並み404エラーになっていることをみつけました。
https://docs.ruby-lang.org/ja/2.4.0/method/ARGF=2eclass/i/binmode.html
上記ページから rdoc リンクを押すと 404 エラーが再現します。
るりまからrdocへの遷移は `ClassName` or `NameSpace1::NameSpace2::ClassName` のパターンはサポートしているが、 `ARGF.class` は想定外の形式だったため404になっていた。
例えば binmode へのリンクの場合、
修正前は
https://docs.ruby-lang.org/en/2.4.0/ARGF.class.html#method-i-binmode
修正後は
https://docs.ruby-lang.org/en/2.4.0/ARGF.html#method-i-binmode
にリンクする。
=> Fix RDCompiler#rdoc_url for ARGF.class

bitclust-core.gemspec, bitclust-dev.gemspec, lib/bitclust/rdcompiler.rb, test/test_rdcompiler.rb, tools/insert-canonical.rb
https://github.com/rurema/bitclust/pull/29/files をみて気づいたのですが、http のままになっていたようなので、https に変更した方が良いのではないかと思いました。
=> Use https for docs.ruby-lang.org

.travis.yml
Rubyの新しいバージョンがリリースされていたので、CIをアップデートします。
https://www.ruby-lang.org/ja/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/ja/news/2017/09/14/ruby-2-4-2-released/
=> CI update to 2.3.5 and 2.4.2

theme/default/style.css
https://docs.ruby-lang.org/ja/latest/library/_builtin.html で
のようにリンクがセルいっぱいになっていなかったのを、
のようにセルいっぱいになるようにする修正です。
一番最後の行が
のようにはみ出してしまうようですが、対処方法がわかりませんでした。
多少不恰好な部分があっても、全体がクリックできるようになる方が利便性が上がって良いのではないかと思っています。
=> Expand link in td

lib/bitclust/preprocessor.rb, test/test_preprocessor.rb
In previous version, output extra "//}\n" with following input
#@samplecode
puts "samplecode for all versions"
#@since 2.4.0
puts "samplecode for 2.4.0"
#@end
#@end
=> Fix preprocessor state

theme/default/style.css
リストの一番下のリンクに hover したとき、枠をはみ出していた。
padding をつけているのに height: 100% としていたのが原因。
box-sizing を指定していないので、padding のぶんだけはみ出す。
=> クラス一覧、メソッド一覧のリンクのスタイルを改善

bitclust-core.gemspec, bitclust-dev.gemspec, lib/bitclust/silent_progress_bar.rb, lib/bitclust/subcommand.rb, lib/bitclust/subcommands/chm_command.rb, lib/bitclust/subcommands/statichtml_command.rb, refe2.gemspec
目的
===
progressbar gemのバージョンを最新のものに上げます。
https://github.com/rurema/bitclust/commit/948504703caf48509cd50c0a143f3bec544f406a でこのgemのバージョンはpinされていますが、コミットメッセージを見る限りだと積極的にpinをしたいわけではないように見えます。
バージョンを上げておくことによって、将来progressbar gemでなにか問題が発生したときにも最新バージョンに追従しやすいようにします。
やったこと
===
https://github.com/rurema/bitclust/commit/dae13343239811f6f3e379e4796b5cdcc80c9fb2
* `ProgressBar.new`ではなく`ProgressBar.create`を使うようになっていたので修正
* `ProgressBar.create`のときにキーワード引数を使うようになっていたので修正
* `SilentProgressBar`の実装を最新の`ProgressBar`に合わせた
* `inc`メソッドを`increment`メソッドにリネーム
* `title.replace`を`title=`メソッドを使用するように修正
* バージョンを上げたことにより、タイトルの長さが自動で調節されなくなっていたので、`align_progress_bar_title`メソッドを追加して修正
* これがないと、下の動画のようになってしまいます。
`align_progress_bar_title`なし
`align_progress_bar_title`あり …
=> Update progressbar gem

data/bitclust/template.offline/layout
https://github.com/rurema/doctree へのリンクをフッターに追加します。
目的
===
「るりまの間違いを見つけたけどどこにPull Requestをしたらいいかわからない…」という人を減らすために、各ページのフッタにGitHubリポジトリへのリンクを追加します。
これによってるりまのドキュメントを書いてくれる人が増えたら嬉しいなと思っています。
実際にフィードバック先がわからないという例もあるようでした。
> そういえば、フィードバック先がわからないという声を聞いたことがあり、とても良いアイデアに思えました！
> https://mobile.twitter.com/koic/status/1120974955238137856
表示方法
===
現在はシンプルに、「フィードバックはこちら」とだけ表示しています。
最初はRails Guideを参考に少し長い文を書いていたのですが、ちょっと違和感があったので短くしました。
文字は書かずにGitHubのアイコンだけをライセンス表示と並べるのもありかなと思ったのですが、画像をどう配置したらいいかがよくわからなかったので試していません。
どう表示するかは結構議論の余地があるところだと思うので、アドバイスをもらえたら嬉しいです。
あまりデザイン力がないのでいい感じのスタイルをあててもらえたりするととても助かります…！
=> Add feedback link to footer

bitclust-core.gemspec, bitclust-dev.gemspec, refe2.gemspec
Gemspecでの`rubyforge_project=`はdeprecatedで消える予定とのことで、gemspecから削除しました。
```bash
$ bundle install
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/pocke/ghq/github.com/rurema/bitclust/refe2.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/pocke/ghq/github.com/rurema/bitclust/bitclust-dev.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/pocke/ghq/github.com/rurema/bitclust/bitclust-core.gems …
```
=> Remove rubyforge_project= from gemspecs

lib/bitclust/preprocessor.rb, test/test_preprocessor.rb
`#@since`などのpreprocessorがネストした時に条件文の評価結果がおかしくなってしまっていたので修正します。
`State#processing?`で1つ前までの条件しか見ていなかったために、条件が3つ以上重なると最初の条件が見られなくなってしまっていました。
これにより、例えばバージョンが2.4.0のときに次のようなコードの`#@until 2.4.0`が無視されて、`Not display here!`が評価されてしまいます。
```
#@until 2.4.0
#@since 1.8.7
#@since 1.9.3
Not display here!
#@end
#@end
#@end
```
実際にこれと同じような現象がるりまの`LIBRARIES`ファイルのtkライブラリについて起きていました。
https://github.com/rurema/doctree/blob/95032ee45837734b0f3a1f8e59f45dec6c17e11e/refm/api/src/LIBRARIES#L656
656行目で`#@until 2.4.0`、679行目で`#@since 1.8.2`、762行目で`#@since 1.8.4`が始まっていて、ネストしているため、最初の`#@until 2.4.0`が無視されていました。
これは`#@since 1.8.x`を消すなかで差分の確認をしていたら、何故かいじっていないはずのtkライブラリの差分が出ていて気が付きました。
https://github.com/rurema/bitclust/pull/32 の以前はstateは`前のstate && 次のstate`を取っていたようなので、それと同じような挙動をするように修正しました。 …
=> Fix nested conditional preprocessors

test/test_syntax_highlighter.rb
Ruby 2.7ではbitclustのテストが通らなくなっています。
```bash
$ bundle exec rake
Loaded suite test
Started
...............................................................................
(snip)
........F
===============================================================================
Failure: test: multiple line(TestSyntaxHighlighter::syntax error)
/home/pocke/ghq/github.com/rurema/bitclust/test/test_syntax_highlighter.rb:18:in `block (2 levels) in <class:TestSyntaxHighlighter>'
15: 
16:     test "multiple line" do
17:       src = "a = 1\n...\n"
=> 18:       assert_raise(BitClust::SyntaxHighlighter::ParseError.new("-", 2, 3, "syntax error, unexpected ..., expecting end-of-input")) do
19:         highlight(src)
20:       end
21:     end
<BitClust::SyntaxHighlighter::ParseError(<-:2:3 syntax error, unexpected …
```
=> Change syntax error example for Ruby 2.7

lib/bitclust/subcommands/setup_command.rb, test/test_functionreferenceparser.rb
Hi. I want to create reference manual with epub version.
Then I found `bitclust setup` create old versions.
I want to create it only in active maintainance versions.
Thanks.
=> Drop EOL version and add newest version.

lib/bitclust/nameutils.rb, lib/bitclust/subcommands/statichtml_command.rb
るりまのビルドをしていて結構時間がかかるなーと思っていたので少し速くしてみました。
このPRの高速化ポイントは2つです。
2b57707
まず、必要のないメソッド呼び出しが結構な時間を食っていたので削除しました。
`create_html_file`などのメソッドが`Pathname#relative_path_from`の結果を戻り値として返していましたが、これはどこからも使われていませんでした。
これらを削除したところ、doctreeレポジトリでの`rake statichtml:2.6.0`の実行が9秒から8.6秒ぐらいまで縮まりました。
だいたい4%ぐらいの速度改善です。
c0429c1
次に、NameUtilsでの`split_method_id`がボトルネックになっているようだったのでキャッシュするようにしました。
このメソッドは https://github.com/rurema/bitclust/blob/c0429c15ea34a166a136cfda55ec42fac5a0e6a8/lib/bitclust/nameutils.rb#L69-L107 のようにあちこちから呼ばれるので、相対的に重い処理となっていたようです。
そして同じ引数で何度も呼ばれているようなのでキャッシュの効果もありました。
この変更によって`rake statichtml:2.6.0`の実行が8.6秒が7.9秒まで縮まりました。
だいたい8%ぐらいの速度改善です。
---
このPR全体では、`rake statichtml:2.6.0`の実行が9.15秒から8.3秒ぐらいまで縮んだので、9%ぐらいの速度改善になりました。(各パッチのベンチマークと全体のベンチマークを取った時期がずれているので、実行時間が少しぶれています🙏) …
=> Make statichtml command faster

theme/default/style.css
* #51 macOS で等倍フォントが使われない問題への対応
* pre タグの余白が統一されていない問題を修正
lillia テーマに関しては確認する方法がわからず手をつけられていません
macOS 10.14.6 / Google Chrome 76.0.3809.132
=> monospace font display optimization (#51)

data/bitclust/template.offline/layout, theme/default/style.css
SEO
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">Rubyでメソッドの使い方を検索したとき、公式ではない公式風APIドキュメントがしれっと公式よりも上に出てくる問題をなんとかしたい。<br>いや、サイトを運営している人が必ずしも悪いわけじゃないけど、Ruby 1.9時代の情報っぽいので、初心者さん殺しの罠になりかねないんだよね・・・。</p>&mdash; Junichi Ito (伊藤淳一) (@jnchito) <a href="https://twitter.com/jnchito/status/1195201871679344641?ref_src=twsrc%5Etfw">November 15, 2019</a></blockquote>
https://docs.ruby-lang.org/ja/latest/doc/index.html をChrome拡張のLighthouseでテストしました。
https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=ja
SEOについては以下のような感じでした
[Lighthouse Report.pdf](https://github.com/rurema/bitclust/files/3855777/Lighthouse.Report.pdf)
> Many search engines rank pages based on how mobile-friendly they are. Without a viewport meta tag, mobile devices render pages at typical …
=> Update theme for smartphone

data/bitclust/catalog/ja_JP.UTF-8, data/bitclust/template.offline/class
#72 を実装してみました。
たとえばArrayでは次のような感じで表示します。
* オーバーライドされているメソッドは表示しません。
* `Array#include?`はArrayに定義されているので、Enumerableのメソッドとしては表示しません。
* `Object`, `Kernel`, `BasicObject`で定義されているメソッドは表示しません
* 試しに表示してみたら結構場所を取る割にあまり意味がないかなと思ったためです。
* メソッドが定義されていないクラスはスキップします
* `Object`以下のクラスを継承していない場合には、このセクションをまるごとスキップします
=> Display ancestor's method in class page

bin/refe
#74 ですが、`$LOAD_PATH` への `lib` の追加をやめるようにしてみました。
空のディレクトリを維持するよりもよいかなと思います。
=> no longer need `lib` for `bin/refe`

data/bitclust/template.offline/layout
offlineのテンプレートのほうが使われていそうに見えるので
https://github.com/ruby/docs.ruby-lang.org/blob/67fcf9c9945adc4419c7e372ce6b1210f6f98bff/system/bc-static-all#L15
関連: https://github.com/rurema/bitclust/pull/78 https://github.com/rurema/doctree/issues/2036
=> Refine HTML title for SEO 2

test/test_syntax_highlighter.rb
Follow up d92b7e754f5864d77e6a2fffd2549c64758b117c
`BitClust::SyntaxHighlighter::ParserError`のメッセージにsrcが含まれるようになったので、テストの方も修正しています。
=> Fix test failing

data/bitclust/template.offline/layout
Slackのruby-jp workspaceのrurema channelで、hanachinさんが
>  Using the meta element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.ruby-lang.org%2Fja%2F2.6.0%2Fdoc%2Findex.html (edited) 
のように[発言していた][1]のを見て、修正しようと考えました。
確かに、既にhtml要素にlang属性でja-JPも指定されているし、この要素は必要なさそうです。
---
念のため、doctree側で以下のコマンドで出力されるHTMLを見て、この変更で該当行が取り除かれることを確認しました。
```
bundle exec bitclust htmlfile --ruby=2.6.0 refm/doc/index.rd
```
生成されたHTMLを https://validator.w3.org/nu/#textarea に入力して確認してみると、件のエラーも出なくなりました。
[1]: https://ruby-jp.slack.com/archives/CM3PCPNQ5/p1575528817163100
=> Remove obsolete meta language element

data/bitclust/template.offline/class, data/bitclust/template.offline/class-index, data/bitclust/template.offline/doc, data/bitclust/template.offline/function, data/bitclust/template.offline/function-index, data/bitclust/template.offline/library, data/bitclust/template.offline/library-index, data/bitclust/template.offline/method, theme/default/style.css
HTMLページ上部のパンくずリスト部分のマークアップ方法を、これまでp要素と`>`の文字で1つの段落として表現していたのを、ol要素とli要素を使って順序付きリストで表現するように変えたいのですが、どうでしょうか。
ナビゲーション用の要素であることが機械からもより理解しやすくなるので、検索インデックス生成用のクローラにも優しいし、将来もう少しメタデータを追記することで、例えばGoogleの検索結果にパンくずリストが表示されるようにもできます。
https://developers.google.com/search/docs/data-types/breadcrumb?hl=ja
=> Change breadcrumb markup from paragraph to ordered list

data/bitclust/template.offline/class, data/bitclust/template.offline/class-index, data/bitclust/template.offline/doc, data/bitclust/template.offline/function, data/bitclust/template.offline/function-index, data/bitclust/template.offline/library, data/bitclust/template.offline/library-index, data/bitclust/template.offline/method, lib/bitclust/screen.rb
JSON-LDでパンくずリストを記述すれば、Googleの検索結果に適切にパンくずリストを表示させられるし、上手くいけば検索順位を上げてくれるかもしれないと思うのですが、どうでしょうか。
https://developers.google.com/search/docs/data-types/breadcrumb?hl=ja
=> Add JSON-LD metadata for breadcrumb navigation

data/bitclust/template.offline/class, data/bitclust/template.offline/class-index, data/bitclust/template.offline/doc, data/bitclust/template.offline/function, data/bitclust/template.offline/function-index, data/bitclust/template.offline/library, data/bitclust/template.offline/library-index, data/bitclust/template.offline/method, theme/default/style.css
#88 を承けて、継承リストを順序付きリストで記述するように変更してみました。ただし、**これまでと比べて記述順序が逆になっています。**
それと、これは些細な変更ですが、dynamic include等の継承リスト以降に続く可能性がある情報について、これまでbr要素とテキストノードで表現されていたのを、それぞれp要素で囲むようにしました。これは、その方が構造的に適切で、かつそうした方がデザインが崩れにくく、結果的に実装しやすかったためです。
- Rubyのコードで継承のコードを書くときは、左が子、右が親になる
- それ故にこれまではこういう記述順になっていたのではないかと思います
- [Googleのドキュメント](https://developers.google.com/search/docs/data-types/breadcrumb?hl=ja)等を見る限り、パンくずリストを順序付きリストで表現するときは、根から順に記述していくのが一般的に見える
- ウェブサイト内の2つのパンくずリストが構造的に別の順序で表記されていると、混乱を招く
- 実装が楽
- グローバルナビゲーションと同じものを使い回せるため
ということを踏まえて考えた結果、これまでの継承リストと記述順序を逆にした方が良いのでは、と思い変更しています。
=> Change class hierarchy markup to ordered-list

data/bitclust/template.offline/method
Close #93 
インスタンスメソッドやクラスメソッドの個別のページの`<title>`タグから、"instance method"や"singleton method"という表記を取り除きます。
これによって`Class#method`のような表記が`<title>`の先頭に来るので、検索結果を見た時やブラウザのタブでの表示が見やすくなるのではと思います。
なお、このPRでは`<body>`の中には変更がありません。
たとえば、青い帯の中のタイトルは変更しておらず、従来どおり"instance method"などが表示されています。
また、メソッド以外のページ(クラス、モジュール、Cの関数など)は変更していません。
これらは文字が充分短い(`class`, `module`, `function`, `macro`)ですし、取り除いてしまうと例えばクラスとモジュールの区別がつかなくなってしまいます。
対してメソッドの場合は`Array.[]`と`Array#[]`のように記号で区別がつくようになっています。
まあこの記号の意味を知らないと区別がつかないのですが、ページにアクセスすれば区別できるし許容できるかなと思っています。
before
after
=> Remove type_label, such as "instance method", from <title> for methods

data/bitclust/template.offline/layout
https://help.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code のように issue 作成を試そうとすると、 permalink というパラメーターがつくようなので、同様につければ良さそうかと思ったのですが、
https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters
にはなかったので、 body に変更したコミットを積んでから pull request を作成しました。
=> Add current url to feedback link

lib/bitclust/screen.rb, lib/bitclust/subcommands/statichtml_command.rb
Ruby 2.7+ で出るwarningを潰しています。
網羅的には対応していないですが、とりあえず目についたところだけ。
=> Fix Ruby 2.7 warnings

lib/bitclust/classentry.rb, lib/bitclust/completion.rb, lib/bitclust/docentry.rb, lib/bitclust/libraryentry.rb, lib/bitclust/methodentry.rb, lib/bitclust/methodid.rb, lib/bitclust/ridatabase.rb
`c.superclass` is nil when c is for BasicObject class at https://github.com/rurema/bitclust/blob/068c5c6ab2a669dbce2e033ca1b278c7c56ba851/lib/bitclust/screen.rb#L536
So sometimes NoMethodError happens at https://github.com/rurema/bitclust/blob/068c5c6ab2a669dbce2e033ca1b278c7c56ba851/lib/bitclust/classentry.rb#L42
I add checking class to every `def ==`.
=> Fix random failures

lib/bitclust/syntax_highlighter.rb, test/test_syntax_highlighter.rb
fix #97
これによって、`String#slice(regexp, name)` 等で正しく表示されていなかったコードが正しく表示されるようになりました。
before
---
after
=> samplecode 内の HTML エスケープ漏れを修正

lib/bitclust/libraryentry.rb, lib/bitclust/methodentry.rb, lib/bitclust/nameutils.rb, lib/bitclust/preprocessor.rb, lib/bitclust/rdcompiler.rb, lib/bitclust/requesthandler.rb, lib/bitclust/ridatabase.rb, lib/bitclust/rrdparser.rb, lib/bitclust/simplesearcher.rb, lib/bitclust/subcommands/methods_command.rb, lib/bitclust/subcommands/server_command.rb, lib/bitclust/subcommands/statichtml_command.rb, packer.rb, setup.rb, test/test_bitclust.rb, tools/bc-checkparams.rb, tools/check-signature.rb
#111 を含めて、前から `-w` だと警告多いなぁと思ってたので、ざっと消してみました。
doctree の `rake check_format` で生成される db-2.[4567].0 と html が同一なのは確認しました。
=> Suppress warnings

data/bitclust/template.offline/layout
#98 を解決します。
`URLSearchParams` が使えるブラウザーでのみこれを使うようにします。
=> IE において，フィードバックリンクのための JavaScript がエラーを出すのを抑制

data/bitclust/template.offline/layout, lib/bitclust/subcommands/statichtml_command.rb, theme/default/script.js, theme/default/style.css
https://github.com/rurema/doctree/issues/1582 に対する実装です。
`#@samplecode` で記述されたサンプルコードの右上に「COPY」ボタンをつけます。
クリックするとクリップボードにコードがコピーされます。
=> サンプルコードに「COPY」ボタンを付ける

lib/bitclust/rdcompiler.rb, lib/bitclust/subcommands/statichtml_command.rb
Fix #108
If the option is specified, the statichtml subcommand doesn't stop on
BitClust::SyntaxHighlighter::ParseError.
=> statichtml: add --no-stop-on-syntax-error option

data/bitclust/template.offline/class, theme/default/style.css
template.offline の class の目次を改善します。スタイルは default を前提とします。
ポイントは以下のとおりです。
- エイリアスを分離してソート<br>例）[Enumerable](https://docs.ruby-lang.org/ja/2.7.0/class/Enumerable.html) で，`inject` の次に `reduce` が掲載され（その次が `lazy`），ABC 順になっていなかった。
- 記号が英数字より前になるようソート<br>例）[Integer](https://docs.ruby-lang.org/ja/2.7.0/class/Integer.html) で `|` と `~` が `upto` のあとに来ていた。
- 重複を排除<br>例）[Kernel](https://docs.ruby-lang.org/ja/2.7.0/class/Kernel.html) で `open` は二つのエントリーに分かれていたので目次にも二つ掲載されていた。
- メソッド名を HTML エスケープ<br>例）[Kernel](https://docs.ruby-lang.org/ja/2.7.0/class/Kernel.html)  の `$<` などのところで正しい HTML になっていなかった。
- 多段組に<br>#102 を解決します。
なお，ソーティングについてはまだ改善の余地があるかも知れません。
例えば `Kernel` の `$0`〜`$11` など数字列だけが異なるものは数の大小順になっていたほうがいいかもしれません。
また，[Encoding](https://docs.ruby-lang.org/ja/2.7.0/class/Encoding.html) で `WINDOWS_31J` と …
=> template.offline の class の目次を改善

data/bitclust/template.offline/class, lib/bitclust/classentry.rb, lib/bitclust/nameutils.rb, lib/bitclust/rrdparser.rb
```
refm/api/src/_builtin/ARGF:1: singleton object class not implemented yet
refm/api/src/webrick/httpproxy/NullReader:1: singleton object class not implemented yet
```
という警告が出ていた singleton object class に対応しました。
db に singleton_object_class として保存するようにしたところ、すべてのクラスで `singleton_object_class=` の行が増えて db のサイズが増えているようなので、 `superclass=` を流用するようにした方が良いかもと思ったので、後で変更します。
クラスの継承リストは singleton object ではなく singleton class から表示するようにしました。
=> Singleton object class を実装

lib/bitclust/preprocessor.rb
現在の `Preprocessor#next_line` の実装では，多数の `when` 節を持った `case` 式で preprocessor directive を処理しています。
数の上で圧倒している「preprocessor directive ではない行」（`#@` で始まらない行）が，10 個の正規表現マッチングを経ないと処理されません。
`Regexp#===` はそれなりに重いので，この `next_line` がいくらか律速になっているようです。
そこで，「`#@` で始まらない行」を `case` 式の先頭で分岐させてみたところ，若干速くなりました。
手許の環境（SSD，macOS，Ruby 2.7.0）で，doctree の `rake generate:2.7.0` が
- real 時間：16 秒程度
- user 時間：8 秒程度
だったのが，この変更により
- real 時間：15 秒程度
- user 時間：7 秒程度
と，real で数 %，user で 1 割以上削減できました。
（大した改善ではありませんが）
なお，Ruby 2.4 以上では，キャプチャーが不要なマッチングで `Regexp#===` の代わりに `Regexp#match?` を使うことができ，こちらのほうが高速です。
この場合，`case` 式の簡潔な記述をあきらめ，
```rb
elsif /\A\#@since\b/.match?(line)
```
みたいなのを並べることになりますが。
いま手許にベンチマークテストの結果がありませんが，以前実験したときは有意な差が出たと記憶しています。
=> Preprocessor の next_line を高速に

data/bitclust/template.offline/layout
HTML5 では
- `<head>`, `</head>` タグは不要
（省略できる条件を厳密に書くとややこしいが，ともかく今の場合は不要）
- stylesheet のリンクに `type="text/css"` は不要
- charset 指定は `<meta charset="...">` で OK
なので，レイアウトファイル（template.offline/layout）を簡素化します。
これにより削減されるファイルサイズは 1 HTML あたり 120 バイト程度で，1 Ruby バージョンの総サイズにしても 1.6 MB 程度しか減りません。
なので大した改善にはならないのですが，無駄な記述は省きたいと思いました。
=> template.offline のレイアウトファイルを若干シンプルに

theme/default/script.js
私のミスですが，サンプルコードの「COPY」ボタンを div 要素で実装していました。
pre 要素に div を入れてはいけないので，これを span 要素に変えます。
修正しなくても見た目や動作に支障はありませんが。
また，不要な行をコメントアウトした個所があり，削除するのを忘れていたので，ついでに削除します。
=> COPY ボタンの要素を div から span へ

data/bitclust/template.offline/class, data/bitclust/template.offline/class-index, data/bitclust/template.offline/doc, data/bitclust/template.offline/function, data/bitclust/template.offline/function-index, data/bitclust/template.offline/layout, data/bitclust/template.offline/library, data/bitclust/template.offline/library-index, data/bitclust/template.offline/method
現在の template.offline では，`header` 要素の次にページタイトルの `h1` が置かれ，フッター部（ライセンスとフィードバック）は `div#footer` でマークアップされ，`main` 要素は用いられていません。
これを以下のように変えます。
- `h1` は `header` に入れる
- フッターは `footer` 要素にする
- `header` と `footer` に挟まれた部分全体を `main` 要素に入れる
この修正は，見た目はとくに変えませんが，HTML5 として自然なマークアップになりますし，また，こうすることでスタイルが当てやすくなります。
たとえば，フッター部を左右と下端にぴったり付けたデザインにしたいとき，現状では `body` のマージンがありますが，これをゼロにするとページコンテンツもマージン無しになってしまいます。
`header`, `main`, `footer` の構成だとそれぞれの `margin`, `padding` がコントロールできます。
つまり，見た目の改善のための準備という意図があります。
=> body の子要素を header, main, footer とし，h1 を header に入れる

data/bitclust/template.offline/library
fix #56
この修正で以下のように English ライブラリの `$FS` などの変数も表示できるようになります。
=> グローバル変数などのエイリアスをライブラリの一覧にすべて表示

data/bitclust/template.offline/class
fix https://github.com/rurema/doctree/issues/2125
この修正で以下のように `Enumerable#to_a` などのメソッドも一覧に表示されるようになります。
=> 継承したメソッドのエイリアスも一覧に表示

data/bitclust/template.offline/layout, data/bitclust/template.offline/method, lib/bitclust/entry.rb, lib/bitclust/methodentry.rb, lib/bitclust/rdcompiler.rb, lib/bitclust/rrdparser.rb, lib/bitclust/screen.rb, lib/bitclust/subcommands/statichtml_command.rb
`--edit-base-url` オプションを付け `statichtml` を実行すると編集用のリンクが表示されます
```
% bundle exec bitclust --database=/tmp/db-2.5.0 statichtml --outputdir=/tmp/html/2.5.0 --templatedir=/home/sei/src/github.com/rurema/bitclust/data/bitclust/template.offline --catalog=/home/sei/src/github.com/rurema/bitclust/data/bitclust/catalog --fs-casesensitive --canonical-base-url=https://docs.ruby-lang.org/ja/latest/ --edit-base-url=https://github.com/rurema/doctree/edit/master/
```
---
メソッドの個別ページに編集用のリンク
---
メソッド一覧のpermalink, rdocの横に編集用のリンク
=> Implement "このマニュアルを編集する"

data/bitclust/template.offline/layout
rurema/doctreeのレポジトリで`statichtml` rake taskを -w 付きで実行すると、 `layout.erb:26: warning: instance variable @edit_url not initialized` という警告が出るのを修正します。
=> Fix uninitialized instance variable warning for `edit_url` ivar

.github/workflows/gempush.yml, bitclust-core.gemspec, bitclust-dev.gemspec, refe2.gemspec
vim-jp slack で [metadata に github_repo を設定すれば良い](https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-rubygems-for-use-with-github-packages#publishing-multiple-packages-to-the-same-repository) と教えてもらったので、再挑戦です。
=> GitHub Packagesへのgem公開再挑戦

lib/bitclust/lineinput.rb
1acaab5a1ed5fa52004b14b5481fb805a4b58329 のコミットで上書きされてしまいリンクが壊れてしまっていた
=> Fix edit link

lib/bitclust/searcher.rb, test/test_searcher.rb
以下のように、`refe` コマンドがエラーになっていたので対処しました。
```
$ env RUBYOPT="-I$PWD/lib" bin/refe 
/var/tmp/git/bitclust/lib/bitclust/searcher.rb:416:in `block in print_packed_names': can't modify frozen String: "" (FrozenError)
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:407:in `each'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:407:in `print_packed_names'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:400:in `print_names'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:351:in `show_class'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:248:in `show_all_classes'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:231:in `search_pattern'
from /var/tmp/git/bitclust/lib/bitclust/searcher.rb:98:in `exec'
from bin/refe:23:in `_main'
from bin/refe:15:in `main'
from bin/refe:33:in …
```
=> do not freeze output buffer that can be modified

data/bitclust/template.offline/class
クラスのページで、表示しているクラスのインスタンスメソッドと継承しているメソッドに同じ名前のメソッドが、どちらでも表示されていることがあったのを修正しています。
すでに表示済みのメソッド名を表示しないようにする対応がありましたが、複数の名前を持つメソッドの考慮が漏れていたようでしたので追加しています。
以下はComplexクラスの例ですが、arg, conjugate, imaginaryなどのメソッドが重複して表示されていましたが、修正後には表示されないようになっています。
**修正前**
---
**修正後**
=> 継承しているメソッドに重複するメソッド名を表示しない

lib/bitclust/syntax_highlighter.rb, test/test_rdcompiler.rb
以下のような `class <<` の後に定数以外の識別子が来るコードを
`#@samplecode` でシンタックスハイライトした際に最後の行が
`p .singleton_method(:foo)Foo` のように崩れて表示されていた。
```ruby
class <<obj
def foo
end
end
p Foo.singleton_method(:foo)
```
定数だけでなく識別子もname_bufferに入れ正しくシンタックスハイライトされるようにした
=> Support syntax highlighting `class << obj`

data/bitclust/template.offline/class
f002722624e759dc4c1215cfb6cb86d69527b109 で一覧から非表示にしたが
その際にclass methodとinstance methodを区別していなかったので直した
=> Fixed a filter that hides undefined ancestor's method on class page

bitclust-core.gemspec
Ruby 3.0からWEBrickが標準ライブラリから削除されるようなので依存関係を追加しました。
=> Add webrick dependency

lib/bitclust/server.rb, lib/bitclust/subcommands/server_command.rb
On docs.ruby-lang.org, gems depended by bitclust are not installed.
=> Do not require WEBrick on top level

lib/bitclust/subcommands/htmlfile_command.rb
https://github.com/rurema/doctree/issues/929#issuecomment-668549738 で `refm/doc/` 以下のファイルの場合は `--force` をつければ良いということだったので、自動でつけるようにしてみました。
自動で設定されると問題があったときに外せないと困るので、 `--no-force` にも対応しました。
=> Use `--force` if the target file is in `refm/doc/`

theme/default/style.css
クラスページの目次の段組みが、FirefoxとInternet Explorerで意図していないであろう表示になっていました。
具体的には、列幅に収まらないメソッド名が2列に渡ってしまう場合がありました。
Google Chrome 87, Firefox 84, Internet Explorer 11での [Hash](https://docs.ruby-lang.org/ja/latest/class/Hash.html) ページの表示（下2つでは`ruby2_keywords_hash?`が2列に分かれている）
これをFirefox, IEでもChromeと同様の表示になるように修正しました。
修正後
=> クラスページ目次の一部ブラウザでの表示崩れを修正

lib/bitclust/syntax_highlighter.rb, test/test_syntax_highlighter.rb
シンボル名が大文字で始まっている場合にシンタックスハイライトが崩れていたのを修正しました。
ref: https://docs.ruby-lang.org/ja/2.7.0/method/Hash/i/merge.html
修正前
修正後
=> Fixed syntax highlighting when a symbol name starts with uppercase

lib/bitclust/subcommands/htmlfile_command.rb
`bitclust htmlfile`コマンドでデフォルトのRubyバージョンの変更です。
現状、指定しない場合は、Ruby 2.0.0の説明として、HTMLファイルが生成されています。
換言すると、`--ruby=2.0.0`と指定されたのと同じ状態で、HTMLファイルが作成されています。
しかし、これは古いバージョンであり、るりまのサポート対象外でもあり、変更した方がいいだろうという考えのPRです。
`@version = RUBY_VERSION`
上記に書き換えることで、バージョン指定をしなかったときに、実行してるRubyのバージョンに合わせてHTMLファイルが生成されます。
以下のコードと揃えました。
[lib/bitclust/subcommands/ancestors_command.rb#L18](https://github.com/rurema/bitclust/blob/131817367901b686296f788dff9b6a345277cf8f/lib/bitclust/subcommands/ancestors_command.rb#L18)
[lib/bitclust/subcommands/methods_command.rb#L18](https://github.com/rurema/bitclust/blob/131817367901b686296f788dff9b6a345277cf8f/lib/bitclust/subcommands/methods_command.rb#L18)
[Machida\.rb \#10](https://machidarb.doorkeeper.jp/events/120193) に参加させてもらったときに、
`bitclust …
=> htmlfileコマンドでのデフォルトのRubyバージョンを変更

.github/workflows/test.yml
GitHub Actions の matrix に Ruby 3.0, 3.1 を追加しました。
また、合わせて以下の不要な処理があったので削除しています。
* Windows 環境で実行していないため、 Windows 用の分岐処理を削除
* setup-ruby で bundler がインストールされるため、独自の処理を削除
=> Add Ruby 3.0, 3.1 in CI

data/bitclust/catalog/ja_JP.UTF-8, data/bitclust/template.epub/class, data/bitclust/template.lillia/class, data/bitclust/template.offline/class, data/bitclust/template/class, lib/bitclust/classentry.rb, lib/bitclust/methodentry.rb, lib/bitclust/rrdparser.rb, test/test_rrdparser.rb
Issue #162
publicメソッドの中にprotectedメソッドが混ざってしまっていたので、
protectedメソッドが独立して表示されるように対応しました。
[![Image from Gyazo](https://i.gyazo.com/4b9fe3f964a06b2808d53b5521637b69.png)](https://gyazo.com/4b9fe3f964a06b2808d53b5521637b69)
[![Image from Gyazo](https://i.gyazo.com/5e157a99d7b6bdbcde4a5528439a1498.png)](https://gyazo.com/5e157a99d7b6bdbcde4a5528439a1498)
正規表現のところで、protectedメソッド等は末尾に余計な空白がついてしまっていたので、`strip`を追加しました。
```ruby
line = "Instance Methods"
line = "Private Instance Methods"
line = "Protected Instance Methods"
case line.sub(/\A==/, '').strip
when /\A((?:public|private|protected)\s+)?(?:(class|singleton|instance)\s+)?methods?\z/i
p $1  # => "Private "
p $2  # => "Instance"
end
```
=> protectedメソッドが独立して表示されるように変更

lib/bitclust/screen.rb, lib/bitclust/subcommands/htmlfile_command.rb
現状、`bitclust htmlfile`コマンドで作成したHTMLファイルの左上に表示されるバージョンが、指定したバージョンとなりません。
`bitclust htmlfile`コマンドで対象となるバージョンが、HTMLファイルの表示に反映されるように変更するPRです。
[![Image from Gyazo](https://i.gyazo.com/738cc127e089cf9eb03423c4fbe9a7d9.png)](https://gyazo.com/738cc127e089cf9eb03423c4fbe9a7d9)
```ruby
@target_version = h[:target_version] || h[:database].propget('version')
```
`screen.rb`のここの`h[:target_version]`が`nil`になってしまっているので、`htmlfile.rb`での`@version`を渡すようにしました。
[Machida\.rb \#10](https://machidarb.doorkeeper.jp/events/120193) に参加した際に、ちょっとした質問としてあがっていた内容です。
また、別件ですが、同様に生成されるHTMLが翻訳前の英語な点もちょっとした質問としてでてました(備忘)。
=> htmlfileで指定のバージョンが表示されるように変更

theme/default/style.css
* macOS Safari 環境で `\` が `¥` 表示になる問題への対応
参考: [Mac/iOS Safariでバックスラッシュを円記号として表示する方法 - teppeis blog](https://teppeis.hatenablog.com/entry/2014/09/safari-backslash-yen-sign)
* どうせなら `font-family` 見直すべきだと思い、最近のOSに合わせてシステムフォントを優先したスタイルに変更しました。
---
ローカルでサーバーを立てる方法がwikiなどを見たのですが分からず、出力したHTMLのCSSリンクを書き換えての確認になっています。
以前のPR #71 と同様のファイルを修正しているので、問題ないと思いますが念の為確認をしていただけると幸いです。
特にWindows環境での確認が一切できておりません。
=> CSS font-family の指定をシステムフォントを優先するように修正

lib/bitclust/syntax_highlighter.rb, test/test_rdcompiler.rb
RubyリファレンスマニュアルのNEWS for Ruby 2.7.0"のサンプルコードで、特異メソッド内に書かれた `Object.new` が `.newObject` と表示されるのを修正しました。
https://docs.ruby-lang.org/ja/latest/doc/news=2f2_7_0.html
以下の変更で `Object.new` でシンタックスハイライトされました。
`BitClust::SyntaxHighlighter#on_kw` メソッドでトークンが `class` の場合、クラス定義が始まるとして `@stack` に `:class` を代入されます。
`BitClust::SyntaxHighlighter#on_op` メソッドで `class <<` を処理する時に、特異メソッドの定義が始まると考えて `@stack` にあるクラス定義を表す `:class` を外しました。
https://github.com/rurema/bitclust/issues/169
=> サンプルコードの特異メソッド内でObject.newが.newObjectと表示されるのを修正

lib/bitclust/rdcompiler.rb, test/test_rdcompiler.rb
リストのインデントがずれることがある問題を修正しました。
Fix: https://github.com/rurema/doctree/issues/2621
インデントがずれる原因は2つありました。
1つはリストの項目中に改行含まれる場合に、その次の項目でインデントレベルが変わると条件判定が行われないためインデントが変わらないという問題でした。
もう1つは2レベル以上インデントが変わる場合の処理が不足していたためでした。この対応で `item_list` メソッドの `indent` パラメーターは不要になったので削除しています。
修正後(GC.html)
修正後(news=2f3_0_0.html)
=> リストのインデントがずれていたのを修正

theme/default/style.css
ページ内リンクを踏んだときなど，スクロール位置が一瞬で変わるのではなく，滑らかにスクロールするようにします。
`scroll-behavior` は IE と Safari を除く主要ブラウザーでサポートされています。サポートされていないブラウザーでは従来どおりとなるだけなので，問題ないと思います。
https://developer.mozilla.org/ja/docs/Web/CSS/scroll-behavior
このような動作にしたい理由は「カッコいいから」とかではなく，このほうがページ内の移動であることが分かりやすく，移動前後の位置関係が把握しやすいことです。
=> scroll-behavior: smooth で滑らかスクロール

lib/bitclust/syntax_highlighter.rb, test/test_syntax_highlighter.rb
サンプルコード内の `class Foo; end` が `class ;Foo end` と表示されるのを修正しました。
以下の変更で `class Foo; end` がその通りに出力されました。
トークン `;` について、改行時と同様に `@name_buffer` を `data` に吐き出す。
`on_sp` および `on_nl` とほぼ同じコードになっており、 `event` を引数に受け取る共通メソッドを設けるべきか悩みました。
なんとなくですが `on_sp` と `on_nl` は異なる処理が追加されることもありそうなので現状通り分けておいて良さそうです。
ですが、 `on_nl` と `on_semicolon` は常に同じ処理であるべきの様に思えます。
`;` は改行代わりの区切り文字であると理解しているためです。
#178
=> サンプルコード内の `class Foo; end` が `class ;Foo end` と表示されるのを修正

lib/bitclust/syntax_highlighter.rb, test/test_syntax_highlighter.rb
fix https://github.com/rurema/bitclust/issues/159
以下のように `%i[]` がシンタックスハイライトされるように対応しました。色はシンボルに合わせています。
`%i` の場合は `qsymbols_beg`, `%I` の場合は `symbols_beg` イベントが実行されていたため、対応するメソッドを追加しました。
=> Support syntax highlighting `%i`, `%I`

.github/workflows/test.yml, bitclust-core.gemspec, lib/bitclust/version.rb
doctree の pull request の CI で head のときにエラーになって、ちゃんと確認できない状態になっているので、 `gemspec` に依存を足して、とりあえず ruby 3.4 でも動くようにしておく。
`drb` を不要なときに読み込まないようにする、 NKF から `String#encode` への移行などの根本的な対応は今度の予定にしておく。
=> Fix error on ruby 3.4
